<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>el_svg</name>
   <tag></tag>
   <elementGuidId>fa84cafd-2227-428c-be04-a5efce773848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//html//body//*[local-name()='svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//body//*[local-name()='svg']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web UI Tests/Tips And Tricks/svg/el_iframe</value>
   </webElementProperties>
</WebElementEntity>
