<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elReporter</name>
   <tag></tag>
   <elementGuidId>1a2a0698-c3f3-4568-9304-c927bc3520e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[.//td/a[.='${issue_key}']]//td[@class='reporter']</value>
   </webElementProperties>
</WebElementEntity>
